### ISSUE TITLE
PSA for those who had previously built Xenko/Stride and are encountering build issues with Focus

### ISSUE THREAD

**Issue by jmkinzer** [phr00t/FocusEngine#112]
I encountered a slew of errors in the build where paths were confused, it could not the nuget package directory, etc.  The fix is trivial:

Nuke anything found here (or if you're using this for other projects, just any lines mentioning Xenko and Stride)
%appdata%\NuGet\NuGet.config
For good measure nuke this too
%appdata%\Xenko

Although theoretically %appdata% should cover it, you might also need to check local and roaming... somehow I had entries in both folders.

After this the engine builds with no issues at all... IIRC more cleanly than Xenko built last time I tried - thanks @phr00t!!

**Comment by phr00t** [comment]
Yeah, it is probably getting a bunch of old Nuget packages confused with Focus ones. Clearing them out will make sure all the Focus ones gets used. Thank you for the tip!
