### ISSUE TITLE
Minimized Vulkan Rendering with Intel HD 630

### ISSUE THREAD

**Issue by phr00t** [phr00t/FocusEngine#51]
Rendering seems to be almost completely empty when using an Intel HD GPU & the Vulkan API. Oddly enough, a very small section in the upper left seems to render colors related to the scene, like if the buffer is a few pixels wide. However, I didn't see any obvious problems with render texture sizes while debugging (but I could have missed something). Empty areas are set to the clear color.

**Comment by phr00t** [comment]
When post processing filters are disabled, the screen is grey (seems to be the background color). There is still a small rectangle of scene-rendered pixels in the upper left:

![small-render](https://user-images.githubusercontent.com/5983470/55677012-46fc3b80-58ae-11e9-812f-3fa568e66afd.png)

**Comment by phr00t** [comment]
Might be related to image layouts?

https://www.reddit.com/r/vulkan/comments/8p5hye/intel_vs_nvidia_issue/

**Comment by phr00t** [comment]
RenderDoc captures of Intel HD frame & NVIDIA frame. Obvious problems arise during the first draw color pass. NVIDIA renders the scene fine at that step, while Intel makes the little dark rectangle in the corner:

[RenderDoc-captures.zip](https://github.com/phr00t/xenko/files/3051091/RenderDoc-captures.zip)

**Comment by phr00t** [comment]
Asking for help on Reddit here: https://www.reddit.com/r/vulkan/comments/bab4hc/small_rectangle_rendered_on_intel_hd_works_fine/

Khronos forum: https://community.khronos.org/t/small-rectangle-with-intel-hd-amd-nvidia-fine-please-help/103879

**Comment by phr00t** [comment]
Reddit to the rescue: "You appear to be ignoring Out Of Date / Sub Optimal returns from presentation.

Are you actually getting these return codes at all? Because if so you need to recreate your framebuffers etc. at the new size."

https://vulkan-tutorial.com/Drawing_a_triangle/Swap_chain_recreation#page_Suboptimal_or_out_of_date_swap_chain

**Comment by phr00t** [comment]
The result of presenting & getting the next image is masked if it isn't an error here:

https://github.com/phr00t/xenko/blob/master/sources/engine/Xenko.Graphics/Vulkan/SwapChainGraphicsPresenter.Vulkan.cs#L154

... and "suboptimal" swap chains are not errors. So, I modified SharpVulkan to see the result of these functions on Intel HD hoping for an answer -- unfortunately, these functions are returning "Success".

The idea was to recreate the swap buffers if there was a problem.. so I've been trying to recreate them anyway. Also unfortunately, recreating the swap buffers doesn't help (nothing changes in the rendering behavior).

**Comment by wozeparrot** [comment]
I can confirm that this also happens on a intel uhd 620.

**Comment by phr00t** [comment]
Fixed with https://github.com/phr00t/xenko/commit/44b9dee8ec2cc8df9de193e52ad3ef98b16a9ef5
